# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Nicholas Handy
title: Computer Engineering
email: nichandy@gmail.com
website: www.nicholashandy.com

# Social links
twitter_username: Nick_Handy
github_username:  nichandy
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: nicholashandy
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Nick and I'm an aspiring computer engineer and cyber security enthusiast. Along with those I also have experience making software and web apps.

  I am most skilled in: <mark>Java Programming</mark>, <mark>Computer Architecture</mark> & <mark>Web Application Development</mark>
  
  I am currently learning: <mark>Hardware Design Principles</mark>, <mark>C Programming</mark> & <mark>AWS</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in programming and computer engineering some of my other interests and hobbies are:
   - Ultimate Frisbee
   - Gaming
   - Drawing
   - Traditional Animation

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
